# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('select', 'Lựa chọn'), ('color', 'Màu sắc'), ('text', 'Văn bản'), ('number', 'Số')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('has_image', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('value_code', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/attributes/')),
                ('display_order', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['attribute__display_order', 'display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_thumbnail', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0.1, max_digits=8)),
                ('option_combinations', models.JSONField(help_text='JSON format: {"Size": "39", "Color": "Đen"}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã danh mục')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='categories/thumbnails/', verbose_name='Ảnh đại diện')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Giá cơ bản')),
                ('model_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã model')),
                ('size_guide_image', models.ImageField(blank=True, null=True, upload_to='products/size_guides/', verbose_name='Ảnh hướng dẫn chọn size')),
                ('rating', models.FloatField(default=0.0, verbose_name='Đánh giá trung bình')),
                ('review_count', models.IntegerField(default=0, verbose_name='Số lượng đánh giá')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brand.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
