# Generated by Django 5.1.6 on 2025-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributeoption',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload ảnh cho tùy chọn này (nếu attribute.has_image = True)', null=True, upload_to='products/attributes/%Y/%m/', verbose_name='Ảnh'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', help_text='Upload ảnh sản phẩm', upload_to='products/gallery/%Y/%m/', verbose_name='Ảnh sản phẩm'),
            preserve_default=False,
        ),
    ]
