# Generated by Django 5.2.8 on 2025-12-08 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('products', '0002_initial'),
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brand.brand', verbose_name='Thương hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_guide_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name='Cửa hàng'),
        ),
        migrations.AlterField(
            model_name='productattributeoption',
            name='attribute',
            field=models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='products.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattributeoption',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productattributeoption',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
        migrations.AlterModelTable(
            name='productattribute',
            table='products_productattribute',
        ),
        migrations.AlterModelTable(
            name='productattributeoption',
            table='products_productattributeoption',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='products_productimage',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='products_productvariant',
        ),
    ]
