# Generated by Django 5.1.6 on 2025-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Ảnh thumbnail cho danh mục', null=True, upload_to='categories/thumbnails/', verbose_name='Ảnh đại diện danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã model'),
        ),
    ]
