# Generated by Django 5.1.6 on 2025-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(choices=[('color', 'Màu Sắc'), ('size', 'Size'), ('material', 'Chất Liệu'), ('style', 'Kiểu dáng'), ('custom', 'Khác')], help_text='VD: Size, Color, Material, Style...', max_length=50, unique=True, verbose_name='Tên thuộc tính'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='type',
            field=models.CharField(choices=[('variant', 'Biến thể'), ('spec', 'Thông số kĩ thuật')], default='variant', max_length=20, verbose_name='Loại thuộc tính'),
        ),
    ]
