# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã vận chuyển')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã vận đơn')),
                ('pick_name', models.CharField(max_length=100, verbose_name='Tên người gửi')),
                ('pick_address', models.CharField(max_length=255, verbose_name='Địa chỉ lấy hàng')),
                ('pick_province', models.CharField(max_length=50, verbose_name='Tỉnh/TP gửi')),
                ('pick_ward', models.CharField(max_length=50, verbose_name='Phường/Xã gửi')),
                ('pick_tel', models.CharField(max_length=20, verbose_name='SĐT người gửi')),
                ('name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ nhận')),
                ('province', models.CharField(max_length=50, verbose_name='Tỉnh/TP nhận')),
                ('ward', models.CharField(max_length=50, verbose_name='Phường/Xã nhận')),
                ('hamlet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Thôn/Ấp')),
                ('tel', models.CharField(max_length=20, verbose_name='SĐT người nhận')),
                ('is_freeship', models.BooleanField(default=False, verbose_name='Freeship')),
                ('pick_date', models.DateField(verbose_name='Ngày lấy dự kiến')),
                ('pick_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tiền thu hộ (COD)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú vận chuyển')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị khai giá')),
                ('transport', models.CharField(default='road', max_length=50, verbose_name='Phương thức (Bay/Bộ)')),
                ('pick_option', models.CharField(choices=[('cod', 'Lấy hàng tại nhà'), ('post', 'Gửi tại bưu cục')], default='cod', max_length=10)),
                ('deliver_option', models.CharField(choices=[('standard', 'Tiêu chuẩn'), ('fast', 'Hỏa tốc')], default='standard', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Chờ lấy hàng'), ('picked', 'Đã lấy hàng'), ('shipped', 'Đang vận chuyển'), ('delivered', 'Giao thành công'), ('failed', 'Giao thất bại'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng trọng lượng (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.suborder', verbose_name='Đơn hàng con')),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('tracking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50, verbose_name='Trạng thái VC')),
                ('location', models.CharField(max_length=255, verbose_name='Vị trí')),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(verbose_name='Thời gian sự kiện')),
                ('carrier_status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('carrier_status_description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('sync_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('shipment', 'timestamp', 'status'), name='unique_shipment_tracking_status')],
            },
        ),
    ]
