# Generated by Django 5.1.6 on 2025-12-16 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_order_address'),
        ('store', '0004_remove_store_phone_addressstore_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi vận chuyển', primary_key=True, serialize=False, verbose_name='Mã vận chuyển')),
                ('tracking_code', models.CharField(blank=True, help_text='Mã theo dõi vận chuyển (nếu có)', max_length=100, null=True, verbose_name='Mã theo dõi')),
                ('pick_date', models.DateField(blank=True, help_text='Ngày lấy hàng từ người gửi', null=True, verbose_name='Ngày lấy hàng')),
                ('pick_money', models.DecimalField(decimal_places=2, default=0.0, help_text='Số tiền thu hộ từ người nhận', max_digits=10, verbose_name='Tiền thu hộ')),
                ('note', models.TextField(blank=True, help_text='Ghi chú thêm về vận chuyển', null=True, verbose_name='Ghi chú')),
                ('value', models.DecimalField(decimal_places=2, help_text='Tổng giá trị của hàng hóa vận chuyển', max_digits=10, verbose_name='Giá trị hàng hóa')),
                ('transport', models.CharField(help_text='Phương tiện được sử dụng để vận chuyển', max_length=50, verbose_name='Phương tiện vận chuyển')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Vận chuyển'), ('out_for_delivery', 'Chờ giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Trả hàng / Hoàn tiền')], default='pending', help_text='Trạng thái hiện tại của vận chuyển', max_length=100, verbose_name='Trạng thái vận chuyển')),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng khối lượng của hàng hóa vận chuyển', max_digits=10, null=True, verbose_name='Tổng khối lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ vận chuyển được tạo', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(blank=True, help_text='Ngày giờ vận chuyển được cập nhật', null=True, verbose_name='Ngày cập nhật')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='store.store', verbose_name='Cửa hàng')),
                ('sub_order', models.OneToOneField(help_text='Đơn hàng con liên kết với vận chuyển này', on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.suborder', verbose_name='Đơn hàng con')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
            ],
            options={
                'verbose_name': 'Vận chuyển',
                'verbose_name_plural': 'Vận chuyển',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_id', models.CharField(max_length=100, verbose_name='Mã vận đơn GHTK')),
                ('partner_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã đơn phía hệ thống')),
                ('carrier_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã trạng thái từ hãng')),
                ('carrier_status_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mô tả trạng thái từ hãng')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Thông báo từ hãng')),
                ('event_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm trạng thái (API)')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm hệ thống lưu')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_response', models.JSONField(verbose_name='Raw API response')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sub_order'], name='shipments_s_sub_ord_2d1fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_code'], name='shipments_s_trackin_f1c65b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['shipment'], name='shipments_s_shipmen_c056c2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['label_id'], name='shipments_s_label_i_a021af_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['carrier_status'], name='shipments_s_carrier_b4061c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['event_time'], name='shipments_s_event_t_871c85_idx'),
        ),
    ]
