# Generated by Django 5.1.6 on 2025-12-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='estimated_deliver_time',
            field=models.CharField(blank=True, help_text='Ví dụ: "Sáng 2025-12-19"', max_length=100, null=True, verbose_name='Thời gian dự kiến giao hàng'),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='estimated_pick_time',
            field=models.CharField(blank=True, help_text='Ví dụ: "Sáng 2025-12-18"', max_length=100, null=True, verbose_name='Thời gian dự kiến lấy hàng'),
        ),
    ]
