# Generated by Django 5.1.6 on 2025-10-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('tracking_id', models.AutoField(help_text='ID duy nhất của bản ghi tracking', primary_key=True, serialize=False, verbose_name='ID tracking')),
                ('status', models.CharField(choices=[('created', 'Created'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], help_text='Trạng thái hiện tại trong lộ trình vận chuyển', max_length=50, verbose_name='Trạng thái lộ trình')),
                ('location', models.CharField(help_text='Vị trí hiện tại của đơn hàng', max_length=255, verbose_name='Vị trí hiện tại')),
                ('details', models.TextField(blank=True, help_text='Mô tả cụ thể về trạng thái hiện tại', null=True, verbose_name='Chi tiết trạng thái')),
                ('timestamp', models.DateTimeField(help_text='Thời gian xảy ra sự kiện trong lộ trình', verbose_name='Thời gian sự kiện')),
                ('carrier_status_code', models.CharField(blank=True, help_text='Mã trạng thái gốc từ API nhà vận chuyển', max_length=50, null=True, verbose_name='Mã trạng thái nhà vận chuyển')),
                ('carrier_status_description', models.TextField(blank=True, help_text='Mô tả trạng thái gốc từ nhà vận chuyển', null=True, verbose_name='Mô tả trạng thái nhà vận chuyển')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Tọa độ vĩ độ của vị trí (nếu có)', max_digits=10, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Tọa độ kinh độ của vị trí (nếu có)', max_digits=11, null=True, verbose_name='Kinh độ')),
                ('estimated_delivery', models.DateTimeField(blank=True, help_text='Thời gian giao hàng dự kiến được cập nhật', null=True, verbose_name='Thời gian giao hàng dự kiến')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian bản ghi tracking được tạo trong hệ thống', verbose_name='Thời gian lưu bản ghi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian bản ghi được cập nhật lần cuối', verbose_name='Thời gian cập nhật')),
                ('api_response', models.JSONField(blank=True, help_text='Phản hồi gốc từ API tracking (để debug)', null=True, verbose_name='Raw API Response')),
                ('sync_at', models.DateTimeField(blank=True, help_text='Thời gian đồng bộ dữ liệu từ API', null=True, verbose_name='Thời gian đồng bộ')),
            ],
            options={
                'verbose_name': 'Lịch sử theo dõi vận chuyển',
                'verbose_name_plural': 'Lịch sử theo dõi vận chuyển',
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vận chuyển', 'verbose_name_plural': 'Vận chuyển'},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pick_district',
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['sub_order'], name='shipments_s_sub_ord_2d1fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_code'], name='shipments_s_trackin_f1c65b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipments_s_created_1bef45_idx'),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='shipment',
            field=models.ForeignKey(help_text='Shipment liên kết với tracking này', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='shipments.shipment', verbose_name='Vận chuyển'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['shipment', 'timestamp'], name='shipments_s_shipmen_78bcec_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['status'], name='shipments_s_status_8832bf_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['timestamp'], name='shipments_s_timesta_fce38d_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['created_at'], name='shipments_s_created_9da263_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmenttracking',
            index=models.Index(fields=['sync_at'], name='shipments_s_sync_at_19a51e_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmenttracking',
            constraint=models.UniqueConstraint(fields=('shipment', 'timestamp', 'status'), name='unique_shipment_tracking_status'),
        ),
    ]
