# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='reviews/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='reviews/videos/thumbnails/')),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đánh giá')),
                ('rating', models.IntegerField(help_text='1-5 sao', verbose_name='Xếp hạng')),
                ('size_accuracy', models.CharField(blank=True, choices=[('true_to_size', 'Đúng size'), ('runs_small', 'Hơi chật'), ('runs_large', 'Hơi rộng')], max_length=20, null=True)),
                ('color_accuracy', models.CharField(blank=True, choices=[('accurate', 'Giống ảnh'), ('lighter', 'Nhạt hơn'), ('darker', 'Đậm hơn')], max_length=20, null=True)),
                ('material_quality', models.CharField(blank=True, choices=[('good', 'Tốt'), ('average', 'Bình thường'), ('bad', 'Kém')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='orders.orderitem', verbose_name='Sản phẩm mua')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
            ],
        ),
    ]
