# Generated by Django 5.2.7 on 2025-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('vnpay', 'VNPay'), ('cod', 'Cash on Delivery')], help_text='Phương thức được sử dụng cho thanh toán.', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
