# Generated by Django 5.2.7 on 2025-12-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Số điện thoại liên hệ', max_length=20, unique=True, verbose_name='Số điện thoại'),
        ),
    ]
