# Generated by Django 5.1.6 on 2025-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Thương hiệu'),
            preserve_default=False,
        ),
    ]
