# Generated by Django 5.1.6 on 2025-09-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi địa chỉ', primary_key=True, serialize=False, verbose_name='Mã địa chỉ')),
                ('detail', models.CharField(help_text='Địa chỉ chi tiết (VD: số nhà, ngõ, đường)', max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, help_text='Đánh dấu nếu đây là địa chỉ mặc định', verbose_name='Địa chỉ mặc định')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi huyện', primary_key=True, serialize=False, verbose_name='Mã huyện')),
                ('name', models.CharField(help_text='Tên huyện (VD: Quận Hoàn Kiếm)', max_length=100, verbose_name='Tên huyện')),
            ],
        ),
        migrations.CreateModel(
            name='Hamlet',
            fields=[
                ('hamlet_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi thôn/xóm', primary_key=True, serialize=False, verbose_name='Mã thôn/xóm')),
                ('name', models.CharField(help_text='Tên thôn/xóm', max_length=100, verbose_name='Tên thôn/xóm')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi đơn hàng', primary_key=True, serialize=False, verbose_name='Mã đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Tổng số tiền của đơn hàng', max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Trạng thái hiện tại của đơn hàng', max_length=10, verbose_name='Trạng thái đơn hàng')),
                ('shipment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Trạng thái vận chuyển của đơn hàng', max_length=10, verbose_name='Trạng thái vận chuyển')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ đơn hàng được tạo', verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi mục đơn hàng', primary_key=True, serialize=False, verbose_name='Mã mục đơn hàng')),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng sản phẩm trong mục đơn hàng', verbose_name='Số lượng')),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Giá của sản phẩm tại thời điểm đặt hàng', max_digits=10, verbose_name='Giá tại thời điểm đặt hàng')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi tỉnh/thành', primary_key=True, serialize=False, verbose_name='Mã tỉnh/thành')),
                ('name', models.CharField(help_text='Tên tỉnh/thành (VD: Hà Nội)', max_length=100, verbose_name='Tên tỉnh/thành')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('sub_order_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi đơn hàng con', primary_key=True, serialize=False, verbose_name='Mã đơn hàng con')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Tổng số tiền của đơn hàng con', max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Trạng thái hiện tại của đơn hàng con', max_length=10, verbose_name='Trạng thái đơn hàng con')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày giờ đơn hàng con được tạo', verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(help_text='ID tự tăng, duy nhất cho mỗi xã', primary_key=True, serialize=False, verbose_name='Mã xã')),
                ('name', models.CharField(help_text='Tên xã (VD: Phường Hàng Trống)', max_length=100, verbose_name='Tên xã')),
            ],
        ),
    ]
