# Generated by Django 5.1.6 on 2025-09-30 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(help_text='Người dùng sở hữu địa chỉ này', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(help_text='Huyện của địa chỉ', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.district', verbose_name='Huyện'),
        ),
        migrations.AddField(
            model_name='address',
            name='hamlet',
            field=models.ForeignKey(blank=True, help_text='Thôn/xóm của địa chỉ (có thể để trống)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='orders.hamlet', verbose_name='Thôn/xóm'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(help_text='Địa chỉ giao hàng của đơn hàng', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.address', verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(help_text='Người mua thực hiện đơn hàng', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người mua'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Đơn hàng mà mục này thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(help_text='Biến thể sản phẩm được đặt hàng', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant', verbose_name='Biến thể sản phẩm'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(help_text='Tỉnh/thành chứa huyện', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='orders.province', verbose_name='Tỉnh/thành'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(help_text='Tỉnh/thành của địa chỉ', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.province', verbose_name='Tỉnh/thành'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='order',
            field=models.ForeignKey(help_text='Đơn hàng chính mà đơn hàng con thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order', verbose_name='Đơn hàng chính'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='seller',
            field=models.ForeignKey(help_text='Người bán thực hiện đơn hàng con', on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to=settings.AUTH_USER_MODEL, verbose_name='Người bán'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_order',
            field=models.ForeignKey(help_text='Đơn hàng con mà mục này thuộc về', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.suborder', verbose_name='Đơn hàng con'),
        ),
        migrations.AddField(
            model_name='ward',
            name='district',
            field=models.ForeignKey(help_text='Huyện chứa xã', on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='orders.district', verbose_name='Huyện'),
        ),
        migrations.AddField(
            model_name='hamlet',
            name='ward',
            field=models.ForeignKey(help_text='Xã chứa thôn/xóm', on_delete=django.db.models.deletion.CASCADE, related_name='hamlets', to='orders.ward', verbose_name='Xã'),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.ForeignKey(help_text='Xã của địa chỉ', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.ward', verbose_name='Xã'),
        ),
    ]
