# Generated by Django 5.1.6 on 2025-12-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='suborder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('vnpay', 'Thanh toán qua VNPAY'), ('qr', 'Thanh toán QR / Chuyển khoản')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
