# Generated by Django 5.2.7 on 2025-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái đơn'),
        ),
        migrations.AlterField(
            model_name='suborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('processing', 'Đang xử lý'), ('shipped', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
