# Generated by Django 5.1.6 on 2025-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_status_remove_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Phí vận chuyển'),
        ),
    ]
