# Generated by Django 5.1.6 on 2025-12-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_suborder_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborder',
            name='payment_status',
        ),
    ]
