# Generated by Django 5.2.7 on 2025-12-17 07:33

from django.db import migrations

def fix_paid_status(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    SubOrder = apps.get_model('orders', 'SubOrder')
    
    # Fix all Orders with status='paid' to 'pending'
    updated_orders = Order.objects.filter(status='paid').update(status='pending')
    print(f"✅ Fixed {updated_orders} Orders with status='paid' → 'pending'")
    
    # Fix all SubOrders with status='paid' to 'processing'
    updated_suborders = SubOrder.objects.filter(status='paid').update(status='processing')
    print(f"✅ Fixed {updated_suborders} SubOrders with status='paid' → 'processing'")

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fix_suborder_paid_status'),
    ]

    operations = [
        migrations.RunPython(fix_paid_status),
    ]
