# Generated by Django 5.1.6 on 2025-12-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_address_remove_order_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount_amount',
        ),
    ]
