# Generated by Django 5.1.6 on 2025-12-15 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_name'),
        ('orders', '0007_remove_orderitem_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_orders', to='address.address', verbose_name='Địa chỉ giao hàng'),
        ),
    ]
