# Generated by Django 5.2.7 on 2025-12-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status_alter_suborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='platform_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giảm giá sàn phân bổ'),
        ),
    ]
