# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0002_initial'),
        ('products', '0002_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='seller',
            field=models.ForeignKey(blank=True, db_column='seller_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='store.store', verbose_name='Cửa hàng sở hữu'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vouchers', to='discount.voucher'),
        ),
        migrations.AddField(
            model_name='ordervoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_vouchers', to='discount.voucher'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='products.category'),
        ),
        migrations.AddField(
            model_name='vouchercategory',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_categories', to='discount.voucher'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='products.product'),
        ),
        migrations.AddField(
            model_name='voucherproduct',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_products', to='discount.voucher'),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherseller',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.voucher'),
        ),
        migrations.AddField(
            model_name='voucherstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_platform_vouchers', to='store.store'),
        ),
        migrations.AddField(
            model_name='voucherstore',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_stores', to='discount.voucher'),
        ),
        migrations.AlterUniqueTogether(
            name='uservoucher',
            unique_together={('user', 'voucher')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchercategory',
            unique_together={('voucher', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherproduct',
            unique_together={('voucher', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherseller',
            unique_together={('voucher', 'seller')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherstore',
            unique_together={('voucher', 'store')},
        ),
    ]
