# Generated by Django 5.2.7 on 2025-12-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_free_shipping',
            field=models.BooleanField(default=False, verbose_name='Miễn phí vận chuyển'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_auto',
            field=models.BooleanField(default=False, verbose_name='Tự động áp'),
        ),
    ]
