# Generated by Django 5.1.6 on 2025-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='seller',
            new_name='store',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('platform', 'Platform'), ('store', 'Store')], help_text='Platform voucher hoặc store voucher', max_length=10, verbose_name='Loại voucher'),
        ),
        migrations.DeleteModel(
            name='VoucherSeller',
        ),
    ]
