# Generated by Django 5.1.6 on 2025-12-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_rename_seller_voucher_store_alter_voucher_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='store',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='per_user_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('platform', 'Platform'), ('store', 'Store')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
