# Generated by Django 5.1.6 on 2025-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_alter_voucher_options_remove_voucher_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_freeship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed'), ('freeship', 'Free Shipping')], max_length=10),
        ),
    ]
