# Generated by Django 5.2.7 on 2025-12-23 13:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0005_voucherreservation_voucherusage'),
        ('store', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservoucher',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vouchercategory',
            options={'verbose_name': 'Voucher - Danh mục áp dụng'},
        ),
        migrations.AlterModelOptions(
            name='voucherproduct',
            options={'verbose_name': 'Voucher - Sản phẩm áp dụng'},
        ),
        migrations.AlterModelOptions(
            name='voucherreservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='voucherstore',
            options={'verbose_name': 'Voucher - Cửa hàng áp dụng (Platform)'},
        ),
        migrations.AlterModelOptions(
            name='voucherusage',
            options={},
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='is_auto',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='type',
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_method_required',
            field=models.CharField(choices=[('all', 'Tất cả hình thức'), ('COD', 'Thanh toán khi nhận hàng (COD)'), ('VNPAY', 'Ví điện tử VNPAY'), ('PAYPAL', 'PayPal')], default='all', max_length=20, verbose_name='Yêu cầu phương thức thanh toán'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='scope',
            field=models.CharField(choices=[('store', 'Voucher của Shop'), ('platform', 'Voucher của Sàn'), ('shipping', 'Voucher Vận chuyển')], default='store', max_length=20, verbose_name='Phạm vi'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_vouchers', to='store.store', verbose_name='Cửa hàng sở hữu'),
        ),
        migrations.AlterField(
            model_name='ordervoucher',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordervoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.voucher'),
        ),
        migrations.AlterField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='discount.voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã code'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Số tiền cố định'), ('percent', 'Phần trăm')], max_length=10, verbose_name='Loại giảm giá'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ngày hết hạn'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_free_shipping',
            field=models.BooleanField(default=False, verbose_name='Là mã Freeship'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giảm tối đa (cho %)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Đơn tối thiểu'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='per_user_limit',
            field=models.IntegerField(default=1, verbose_name='Giới hạn mỗi người'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='start_date',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tổng lượt dùng toàn sàn'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã ID'),
        ),
        migrations.AlterField(
            model_name='voucherreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voucherreservation',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.voucher'),
        ),
        migrations.AlterField(
            model_name='voucherstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_vouchers', to='store.store'),
        ),
        migrations.AlterField(
            model_name='voucherstore',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicable_stores', to='discount.voucher'),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucherusage',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
