# Generated by Django 5.1.6 on 2025-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0006_voucher_is_freeship_alter_voucher_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
