# Generated by Django 5.1.6 on 2025-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0007_voucher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
