# Generated by Django 5.1.6 on 2025-12-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0008_voucher_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='is_freeship',
        ),
    ]
