# Generated by Django 5.2.7 on 2025-12-16 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_status_alter_suborder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã yêu cầu')),
                ('return_type', models.CharField(choices=[('refund', 'Trả hàng hoàn tiền'), ('exchange', 'Đổi hàng')], default='refund', max_length=20, verbose_name='Loại yêu cầu')),
                ('reason', models.CharField(choices=[('wrong_item', 'Giao sai sản phẩm'), ('damaged', 'Hàng bị hỏng/lỗi'), ('not_as_described', 'Không đúng mô tả'), ('size_issue', 'Không vừa size'), ('changed_mind', 'Đổi ý không muốn mua'), ('quality_issue', 'Chất lượng kém'), ('other', 'Lý do khác')], max_length=50, verbose_name='Lý do')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số tiền hoàn')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt - Chờ gửi hàng'), ('rejected', 'Từ chối'), ('shipping_back', 'Đang gửi hàng về'), ('received', 'Shop đã nhận hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('return_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã vận đơn trả hàng')),
                ('shop_response', models.TextField(blank=True, null=True, verbose_name='Phản hồi của shop')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='Lý do từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người mua')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Đơn hàng')),
                ('sub_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.suborder', verbose_name='Đơn hàng con')),
            ],
            options={
                'verbose_name': 'Yêu cầu trả hàng',
                'verbose_name_plural': 'Yêu cầu trả hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Số lượng trả')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='orders.orderitem', verbose_name='Sản phẩm đơn hàng')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest', verbose_name='Yêu cầu trả hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm trả hàng',
                'verbose_name_plural': 'Sản phẩm trả hàng',
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/', verbose_name='Ảnh')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.returnrequest', verbose_name='Yêu cầu trả hàng')),
            ],
            options={
                'verbose_name': 'Ảnh trả hàng',
                'verbose_name_plural': 'Ảnh trả hàng',
            },
        ),
        migrations.CreateModel(
            name='ReturnTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Trạng thái')),
                ('note', models.TextField(verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='returns.returnrequest', verbose_name='Yêu cầu trả hàng')),
            ],
            options={
                'verbose_name': 'Lịch sử trả hàng',
                'verbose_name_plural': 'Lịch sử trả hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
