# Generated by Django 5.2.7 on 2025-12-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_suborder_status'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='exchange_order',
            field=models.ForeignKey(blank=True, help_text='Order mới được tạo khi type=exchange', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_from_returns', to='orders.order', verbose_name='Đơn hàng đổi'),
        ),
    ]
