"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import os

load_dotenv()
#  GHTK
GHTK_API_TOKEN = os.getenv("GHTK_API_TOKEN")
GHTK_PARTNER_CODE = os.getenv("GHTK_PARTNER_CODE")
GHTK_BASE_URL = os.getenv(
    "GHTK_BASE_URL",
    "https://services.giaohangtietkiem.vn"
)
# PAYMENT- VNPAY
VNP_URL =os.getenv("VNP_URL", "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html")
VNP_TMN_CODE =os.getenv("VNP_TMN_CODE")
VNP_HASH_SECRET =os.getenv("VNP_HASH_SECRET")
VNP_RETURN_URL =os.getenv("VNP_RETURN_URL", "https://m2smm85s-3000.asse.devtunnels.ms/api/payment/vnpay/return")
VNP_IPN_URL =os.getenv("VNP_IPN_URL","https://m2smm85s-3000.asse.devtunnels.ms/api/payment/vnpay/ipn")
VNP_RETURN_URL_STORE=os.getenv("VNP_RETURN_URL_STORE","https://m2smm85s-3000.asse.devtunnels.ms/seller/dashboard")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = "users.User"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-comt3wg=&xj9(xkg*rzl$p$nwr-8nxavr*i@niopu7n_dixjz0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Thêm CORS support
    "graphene_django",
    "graphene_file_upload",  # Thêm để support file upload trong GraphQL
    "users",     
    "store",     # Thêm app store
    "products",   
    "collection", # Thêm app collection
    "cart",      # Thêm app cart
    "orders",    
    "payments",   
    "shipments",
    "reviews",
    "discount",
    "address",
    "brand",
    "settlements",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS phải ở đầu
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.jwt_middleware.JWTAuthenticationMiddleware',  # JWT Authentication
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# GraphQL Configuration
GRAPHENE = {
    "SCHEMA": "graphql.api.schema",  # Đường dẫn đến schema
}
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
import os
import dj_database_url
from pathlib import Path
import dj_database_url
import os

# DATABASES = {
#     'default': dj_database_url.config(
#         default="postgresql://shoexdata_user:9iJnTZrmoK5e2BmONYOO8kStol4xgeRe@dpg-d35s6dali9vc738mdev0-a.oregon-postgres.render.com/shoexdata",
#         conn_max_age=600,
#         ssl_require=True
#     )
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shoex',        # tên database bạn tạo local (vd: shoexdata)
        'USER': 'postgres',         # user mặc định PostgreSQL local
        'PASSWORD': 'admin',# thay bằng mật khẩu bạn đặt khi cài PostgreSQL
        'HOST': 'localhost',        # local database
        'PORT': '5432',             # cổng mặc định PostgreSQL
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration - Cho phép frontend truy cập
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js frontend
    "http://127.0.0.1:3000",
]

# Hoặc cho phép tất cả (CHỈ cho development)
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Session settings for cross-domain support
SESSION_COOKIE_SAMESITE = 'Lax'  # Lax cho phép cookies từ localhost và 127.0.0.1
SESSION_COOKIE_SECURE = False  # Set True if using HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_DOMAIN = None  # None để hỗ trợ cả localhost và 127.0.0.1
SESSION_SAVE_EVERY_REQUEST = True  # Ensure session is saved on each request

