# Generated by Django 5.2.7 on 2025-11-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã địa chỉ')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('ward', models.CharField(max_length=100, verbose_name='Xã/Phường')),
                ('hamlet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thôn/Xóm/Quận/Huyện')),
                ('detail', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
            ],
            options={
                'verbose_name': 'Địa chỉ người dùng',
                'verbose_name_plural': 'Danh sách địa chỉ',
                'db_table': 'address_address',
                'ordering': ['-is_default', '-address_id'],
            },
        ),
    ]
