# Generated by Django 5.1.6 on 2025-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Số điện thoại liên hệ kèm theo địa chỉ', max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
    ]
