# Generated by Django 5.1.6 on 2025-12-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(help_text='Tên người nhận hàng tại địa chỉ này', max_length=255, null=True, verbose_name='Tên người nhận'),
        ),
    ]
