# Generated by Django 5.2.7 on 2025-12-11 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Sản phẩm trong giỏ hàng', 'verbose_name_plural': 'Sản phẩm trong giỏ hàng'},
        ),
    ]
