# Generated by Django 5.1.6 on 2025-12-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_order_address'),
        ('store', '0004_remove_store_phone_addressstore_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('settlement_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('cancelled', 'Huỷ')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('settlement_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='settlements.settlement')),
                ('sub_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_item', to='orders.suborder')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('paid', 'Đã hoàn'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.suborder')),
                ('settlement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='settlements.settlementitem')),
            ],
        ),
    ]
