# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.CharField(help_text='Mã định danh duy nhất (VD: SHOP-001)', max_length=50, primary_key=True, serialize=False, verbose_name='Mã cửa hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cửa hàng')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(verbose_name='Địa chỉ hiển thị')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='store/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store/covers/')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('followers_count', models.IntegerField(default=0)),
                ('products_count', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cửa hàng',
                'verbose_name_plural': 'Cửa hàng',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/gallery/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressStore',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/TP')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('hamlet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thôn/Xóm')),
                ('detail', models.CharField(max_length=255, verbose_name='Chi tiết')),
                ('is_default', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.store')),
            ],
            options={
                'verbose_name': 'Địa chỉ kho hàng',
            },
        ),
        migrations.CreateModel(
            name='StoreFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='store.store')),
            ],
            options={
                'verbose_name': 'Người theo dõi',
            },
        ),
    ]
