# Generated by Django 5.2.7 on 2025-11-25 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storefollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeimage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.store'),
        ),
        migrations.AddConstraint(
            model_name='addressstore',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('store',), name='unique_default_address_per_store'),
        ),
        migrations.AlterUniqueTogether(
            name='storefollower',
            unique_together={('store', 'user')},
        ),
    ]
