# Generated by Django 5.1.6 on 2025-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_addressstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AddField(
            model_name='addressstore',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
    ]
